#--git-repo git@github.com:missinglinkai/ZSSR-shadow-repo.git
command: 'python main.py'
#git_repo: 'git@github.com:missinglinkai/ZSSR-shadow-repo.git'
data_volume: data_volume_ID
data_query: '@version:data_volume_version @path:067/*'
gpu: true
org: 'missinglinkdemo'
project: 'project_ID'
